version: '3.1'

services:
  world_x:
    image: mysql
    environment:
      MYSQL_DATABASE: 'mysql_db'
      MYSQL_USER: bcuser
      MYSQL_PASSWORD: Password02
      MYSQL_ROOT_PASSWORD: Password02
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: unless-stopped
volumes:
  mysql-volume: