swagger: "2.0"
info:
  description: "Spring REST API course"
  version: "1.0.0"
  title: "Employee Management System"
basePath: "/springRest/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /api/employees:
    get:
      summary: "Get a list of all employees"
      description: "Returns a list of all employees in the system"
      operationId: "showAllEmployees"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Employee"
      tags:
        - "Employee"
  /api/employees/{id}:
    get:
      summary: "Get employee by ID"
      description: "Return employee"
      operationId: "showEmployee"
      parameters:
        - name: "id"
          in: path
          required: true
          type: integer
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Employee"

definitions:
  Employee:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Employee ID"
      name:
        type: "string"
        description: "Employee name"
      email:
        type: "string"
        description: "Employee email"
